import{a as b,S,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const q="50801128-9bde19728bc3e6666ae5ca17b";async function f(o,t){const r=new URLSearchParams({key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}),e=(await b.get(`https://pixabay.com/api/?${r}`)).data;if(e.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return e}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(r=>`
      <li class="gallery-item">
      <a href="${r.largeImageURL}">
      <img class="img" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="wrapper">
     <p class="text">Likes<span class="span">${r.likes}</span></p>
        <p class="text">Views<span class="span">${r.views}</span></p>
        <p class="text">Comments<span class="span">${r.comments}</span></p>
        <p class="text">Downloads<span class="span">${r.downloads}</span></p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),v.refresh()}function P(){m.innerHTML=""}function w(){y.style.display="block"}function p(){y.style.display="none"}function l(){h.classList.add("hidden")}function x(){h.classList.remove("hidden")}const L=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more-btn");let i="",a=1;const B=15;let d=0;function E(o,t){return Math.ceil(o/t)}L.addEventListener("submit",I);p();l();async function I(o){if(o.preventDefault(),i=$.value.trim(),a=1,!i){c.warning({message:"Please enter a search query"});return}P(),w(),l();try{const t=await f(i,a),{hits:r,totalHits:n}=t;d=E(n,B),g(r),a>=d?l():x()}catch(t){c.error({message:t.message})}finally{p(),L.reset()}}M.addEventListener("click",async()=>{a++,w();try{const o=await f(i,a);g(o.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}a>=d&&(l(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}});
//# sourceMappingURL=index.js.map
