import{a as L,S as b,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const S="50801128-9bde19728bc3e6666ae5ca17b";function p(o,t){const r=new URLSearchParams({key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return L.get(`https://pixabay.com/api/?${r}`).then(({data:n})=>{if(n.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return n})}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more-btn"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(r=>`
      <li class="gallery-item">
      <a href="${r.largeImageURL}">
      <img class="img" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="wrapper">
     <p class="text">Likes<span class="span">${r.likes}</span></p>
        <p class="text">Views<span class="span">${r.views}</span></p>
        <p class="text">Comments<span class="span">${r.comments}</span></p>
        <p class="text">Downloads<span class="span">${r.downloads}</span></p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function v(){f.innerHTML=""}function g(){m.style.display="block"}function l(){m.style.display="none"}function u(){y.classList.add("hidden")}function P(){y.classList.remove("hidden")}const w=document.querySelector(".form"),x=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more-btn");let i="",a=1;const $=15;function B(o,t){return Math.ceil(o/t)}w.addEventListener("submit",E);l();u();async function E(o){if(o.preventDefault(),v(),g(),u(),i=x.value.trim(),!i){c.warning({message:"Please enter a search query"}),l();return}try{const t=await p(i,a),{hits:r,totalHits:n}=t,e=15;h(r),a>=Math.ceil(n/e)?u():P()}catch(t){c.error({message:t.message})}finally{l(),w.reset()}}M.addEventListener("click",async()=>{a++,g();try{const o=await p(i,a);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}a>=B(o.totalHits,$)&&(u(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{l()}});
//# sourceMappingURL=index.js.map
